[tool.commitizen]
name = "cz_customize"
tag_format = "$version"
version_scheme = "semver"
version = "0.0.1"
major_version_zero = true

style = [
    ["qmark", "fg:#ffc900 bold"],
    ["question", "bold"],
    ["answer", "fg:#ffc900 bold"],
    ["pointer", "fg:#ffc900 bold"],
    ["highlighted", "fg:#ffc900 bold"],
    ["selected", "fg:#ff6639"],
    ["separator", "fg:#ff6639"],
    ["instruction", ""],
    ["text", ""],
    ["disabled", "fg:#666a84 italic"]
]

[tool.commitizen.customize]
message_template = "{{change_type}}{% if scope %}({{scope}}){% endif %}: {{message}}"
example = "feature: this feature enable customize through config file"
schema = "<type>(<scope>): <body>"
schema_pattern = "(new|add|update|fix|feat|style)(\\([^()\\r\\n]*\\)):(\\s.*)"
bump_pattern = "^(break|new|fix|hotfix)$"
bump_map = {}
change_type_order = []
info_path = "cz_customize_info.txt"
info = """
This is customized info
"""
commit_parser = "^(?P<change_type>feature|bug fix)(?:\\((?P<scope>[^()\\r\\n]*)\\))?:\\s(?P<message>.*)?"
changelog_pattern = "^(feature|bug fix)?(!)?"
change_type_map = {"feature" = "Feat", "bug fix" = "Fix"}

[[tool.commitizen.customize.questions]]
type = "list"
name = "change_type"
choices = ["update", "new", "add", "fix", "feat", "style"]
message = "Type of change:"

[[tool.commitizen.customize.questions]]
type = "input"
name = "scope"
message = "Class or file name: (press [enter] to skip)"

[[tool.commitizen.customize.questions]]
type = "input"
name = "message"
message = "Message:"
